export const ADD_ITEM_CART = 'ADD_ITEM_CART'; //constant for adding to cart
export const REMOVE_ITEM_CART = 'REMOVE_ITEM_CART';

export const TRANSACTION_CREATE_REQUEST = 'TRANSACTION_CREATE_REQUEST';
export const TRANSACTION_CREATE_SUCCESS = 'TRANSACTION_CREATE_SUCCESS';
export const TRANSACTION_CREATE_FAIL = 'TRANSACTION_CREATE_FAIL';
export const TRANSACTION_CREATE_RESET = 'TRANSACTION_CREATE_RESET';
export const TRANSACTION_LIST_REQUEST = 'TRANSACTION_LIST_REQUEST';
export const TRANSACTION_LIST_SUCCESS = 'TRANSACTION_LIST_SUCCESS';
export const TRANSACTION_LIST_FAIL = 'TRANSACTION_LIST_FAIL';